### ISSUE TITLE
Update Slack invite link

### ISSUE THREAD

**Issue by aj-stein-nist** [efabless/chipcraft---mest-course#1]
Per discussion from one of today's in-person training sessions with this material, I would appreciate if the invitation link for Slack in the README is updated. Upon clicking [the current link](https://join.slack.com/t/open-source-silicon/shared_invite/zt-2c9f63e7o-qTuD2jN9u0gcH8BAAzzJeQ), the browser redirects to a page with the following error message.

> This link is no longer active
>
> To join this workspace, you’ll need to ask the person who originally invited you for a new link.

**Comment by stevehoover** [comment]
Oh, I thought I corrected that during class. I'll test in the morning.

**Comment by aj-stein-nist** [comment]
Fixed in https://github.com/efabless/chipcraft---mest-course/commit/6974c66580efe90aa9d27555a6b29321f81dfe77, closing. Thanks for your help, Steve.
